# Define um grupo de servidores backend (upstream) chamado "games_api"
# Esse grupo será usado para balancear carga entre os containers games1, games2 e games3
upstream games_api {
    # Cada "server" representa um container da aplicação Java escutando na porta 9001
    server games1:9001;
    server games2:9001;
    server games3:9001;
}

# Define um novo servidor virtual (virtual host)
server {
    # Porta onde este servidor escutará requisições HTTP (nesse caso, porta interna 8080)
    listen 8080;

    # Tudo que COMEÇA com /api vai para games_api
    location / {
        # Encaminha a requisição para o grupo "games_api" definido acima
        proxy_pass http://games_api/;
        # Preserva o cabeçalho "Host" original da requisição. Ex.: Host: example.com(mesmo digitando examplo.com/abc/def)
        proxy_set_header Host $host;
        # Passa o IP real do cliente para o backend. Ex.: X-Real-IP: 192.168.1.100
        proxy_set_header X-Real-IP $remote_addr;
        # Adiciona o IP do cliente à cadeia de proxies no cabeçalho "X-Forwarded-For". Ex.: X-Forwarded-For: 192.168.1.100, 203.0.113.5, 10.1.1.20
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}