# Define um novo servidor virtual (virtual host)
server {
  # Porta onde este servidor escutará requisições HTTP (diferente da porta padrão 80)
  listen 8080;

  # Nome do host aceito por este servidor (neste caso, "localhost")
  server_name localhost;

  # Define o que fazer quando o path da URL for "/"
  location / {
    # Diretório raiz dos arquivos que serão servidos por este servidor virtual
    root /usr/share/nginx/server1;
    # Arquivo padrão a ser servido quando a URL não especificar um nome de arquivo
    index index.html;
  }
}
