# Define um novo servidor virtual (virtual host)
server {
    # Porta onde este servidor escutará requisições HTTP (diferente da porta padrão 80)
    listen 8081;

    # Nome do host aceito por este servidor (neste caso, "localhost")
    server_name localhost;

    # Define o que fazer quando o path da URL for "/"
    location / {
        # Diretório raiz dos arquivos que serão servidos por este servidor virtual
        root /usr/share/nginx/server1;
        # Arquivo padrão a ser servido quando a URL não especificar um nome de arquivo
        index index.html;
    }

    # Define que os códigos de erro 400, 401 e 404 serão tratados com a página /error40x.html
    error_page   400 401 404  /error40x.html;
    # Define um bloco de localização exato para /error40x.html
    location = /error40x.html {
        # Diretório onde o arquivo de erro está localizado
        root   /usr/share/nginx/error;
    }

    # Define que os códigos de erro 500, 502, 503 e 504 serão tratados com a página /error50x.html
    error_page   500 502 503 504  /error50x.html;
    # Define um bloco de localização exato para /error50x.html
    location = /error50x.html {
        # Diretório onde o arquivo de erro está localizado
        root   /usr/share/nginx/error;
    }
}
