services:
  nginx:
    image: nginx:1.26
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
      - ./settings/servers/proxy-reverse.conf:/etc/nginx/servers/proxy-reverse.conf:ro
      - ./web/error:/usr/share/nginx/error
    restart: unless-stopped
    depends_on:
      - nginx-java-balancer
      - nginx-laravel
      - server1
      - server2
    networks:
      - reverse-proxy

  server1:
    image: nginx:1.26
    container_name: server1-html
    expose:
      - "8081"
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
      - ./settings/servers/server1-html.conf:/etc/nginx/servers/server1-html.conf
      - ./web/server1:/usr/share/nginx/server1
      - ./web/error:/usr/share/nginx/error
    restart: unless-stopped
    networks:
      - reverse-proxy
      - static-content

  server2:
    image: nginx:1.26
    container_name: server2-css
    expose:
      - "8082"
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
      - ./settings/servers/server2-css.conf:/etc/nginx/servers/server2-css.conf
      - ./web/server2:/usr/share/nginx/server2
      - ./web/error:/usr/share/nginx/error
    restart: unless-stopped
    networks:
      - reverse-proxy
      - static-content

  nginx-java-balancer:
    image: nginx:1.26
    container_name: nginx-java-balancer
    expose:
      - "8080"
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
      - ./settings/servers/nginx-java-balancer.conf:/etc/nginx/servers/nginx-java-balancer.conf
    restart: unless-stopped
    networks:
      - reverse-proxy
      - java

  games1:
    build:
      context: ./java/games1
      dockerfile: docker/Dockerfile
    container_name: games1-app
    expose:
      - "9001"
    restart: unless-stopped
    networks:
      - java

  games2:
    build:
      context: ./java/games2
      dockerfile: docker/Dockerfile
    container_name: games2-app
    expose:
      - "9001"
    restart: unless-stopped
    networks:
      - java

  games3:
    build:
      context: ./java/games3
      dockerfile: docker/Dockerfile
    container_name: games3-app
    ports:
      - "9001:9001"
    restart: unless-stopped
    networks:
      - java

  nginx-laravel:
    image: nginx:1.26
    container_name: nginx-laravel
    expose:
      - "8083"
    volumes:
      - ./settings/nginx.conf:/etc/nginx/nginx.conf
      - ./settings/servers/laravel.conf:/etc/nginx/servers/laravel.conf
      - ./php/laravel1:/var/www
    depends_on:
      - laravel1
    networks:
      - reverse-proxy
      - laravel

  laravel1:
    build:
      context: ./php/laravel1
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    expose:
      - "9000"
    volumes:
      - ./php/laravel1:/var/www
    command: [ "/usr/local/bin/entrypoint.sh" ]
    networks:
      - laravel

networks:
  static-content:
    driver: bridge
  java:
    driver: bridge
  laravel:
    driver: bridge
  reverse-proxy:
    driver: bridge