# Bloco obrigatório que configura o sistema de eventos do NGINX
events {}

# Início do bloco principal de configuração HTTP
http {
    # Define um servidor virtual (virtual host)
    server {
        # Porta onde o servidor irá escutar requisições HTTP (padrão: 80)
        listen 80;
        # Nome do host que será aceito por este servidor (ex: localhost)
        server_name localhost;

        # Define o que fazer quando o path da URL for "/"
        location / {
            # Diretório raiz dos arquivos que serão servidos (ex: HTML, CSS, JS)
            root /usr/share/nginx/html;
            # Arquivo padrão a ser servido quando a URL não especificar um nome de arquivo
            index index.html;
        }
    }
    # Virtual hosts a partir da pasta "servers"
    include /etc/nginx/servers/*.conf;
}
