# Bloco obrigatório que configura o sistema de eventos do NGINX
events {}

# Início do bloco principal de configuração HTTP
http {
    # Inclui o arquivo padrão do NGINX com os tipos MIME, que associa extensões (.css, .js etc.) aos seus Content-Type corretos
    include       mime.types;
    # Tipo de conteúdo padrão usado quando a extensão do arquivo não é reconhecida na lista mime.types
    default_type  application/octet-stream;
    # Virtual hosts a partir da pasta "servers"
    include /etc/nginx/servers/*.conf;
}
